### ISSUE TITLE
We need a comment system!

### ISSUE THREAD

**Issue by bytezzz** [bytezzz/peiyangflyer#1]
Let's add this module through the instructions in [this](https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/).

**Comment by bytezzz** [comment]
@ChrisVicky Please help me on this!!

**Comment by jinfanchris** [comment]
Done 
![image](https://raw.githubusercontent.com/ChrisVicky/image-bed/main/2024-03/CommentsComplete.png)
